<!-- Container for the image gallery -->
<div class="container">

  <!-- Full-width images with number text -->
  <div class="mySlides">
    <div class="numbertext">1 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_144736.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">2 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_144805.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">3 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_144940.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">4 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_144956.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">5 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145017.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">6 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145059.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">7 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145223.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">8 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145245.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">9 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145311.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">10 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145520.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">11 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145551.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">12 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_145618.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">13 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_150650.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">14 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_150711.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">15 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_160842.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">16 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_161304.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">17 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_161339.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">18 / 46</div>
      <img src="foto/2023-10_SSLT/20231021_180206.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">19 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_093022.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">20 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_093039.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">21 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_103740.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">22 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_104235.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">23 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_105059.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">24 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_105143.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">25 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_105153.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">26 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_105212.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">27 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_105309.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">28 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152646.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">29 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152743.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">30 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152809.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">31 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152825.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">32 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152858.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">33 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_152932.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">34 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_153125.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">35 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_173556.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">36 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_173629.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">37 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_173828.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">38 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_173903.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">39 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_A1.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">40 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_A2.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">41 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_A3.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">42 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_A4.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">43 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_B1.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">44 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_B2.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">45 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_B3.jpg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">46 / 46</div>
      <img src="foto/2023-10_SSLT/20231022_B4.jpg" style="width:100%">
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>

  <!-- Image text -->
<!--
  <div class="caption-container">
    <p id="caption"></p>
  </div>
-->

  <!-- Thumbnail images -->
<!--
  <div class="row">
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_144636.jpg" style="width:100%" onclick="currentSlide(1)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_150711.jpg" style="width:100%" onclick="currentSlide(2)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231022_105309.jpg" style="width:100%" onclick="currentSlide(3)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_144805.jpg" style="width:100%" onclick="currentSlide(4)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_160842.jpg" style="width:100%" onclick="currentSlide(5)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231022_152646.jpg" style="width:100%" onclick="currentSlide(6)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_144940.jpg" style="width:100%" onclick="currentSlide(7)" alt="">
    </div>
    <div class="column">
      <img class="demo cursor" src="foto/2023-10_SSLT/20231021_161304.jpg" style="width:100%" onclick="currentSlide(8)" alt="">
    </div>
  </div>
-->
</div>

<script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("demo");
  let captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>

