<!-- Container for the image gallery -->
<div class="container">

  <!-- Full-width images with number text -->
  <div class="mySlides">
    <div class="numbertext">1 / 33</div>
      <img src="foto/2024-03_CIG/01.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">2 / 33</div>
      <img src="foto/2024-03_CIG/02.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">3 / 33</div>
      <img src="foto/2024-03_CIG/03.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">4 / 33</div>
      <img src="foto/2024-03_CIG/04.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">5 / 33</div>
      <img src="foto/2024-03_CIG/05.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">6 / 33</div>
      <img src="foto/2024-03_CIG/06.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">7 / 33</div>
      <img src="foto/2024-03_CIG/07.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">8 / 33</div>
      <img src="foto/2024-03_CIG/08.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">9 / 33</div>
      <img src="foto/2024-03_CIG/09.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">10 / 33</div>
      <img src="foto/2024-03_CIG/10.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">11 / 33</div>
      <img src="foto/2024-03_CIG/11.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">12 / 33</div>
      <img src="foto/2024-03_CIG/12.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">13 / 33</div>
      <img src="foto/2024-03_CIG/13.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">14 / 33</div>
      <img src="foto/2024-03_CIG/14.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">15 / 33</div>
      <img src="foto/2024-03_CIG/15.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">16 / 33</div>
      <img src="foto/2024-03_CIG/16.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">17 / 33</div>
      <img src="foto/2024-03_CIG/17.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">18 / 33</div>
      <img src="foto/2024-03_CIG/18.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">19 / 33</div>
      <img src="foto/2024-03_CIG/19.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">20 / 33</div>
      <img src="foto/2024-03_CIG/20.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">21 / 33</div>
      <img src="foto/2024-03_CIG/21.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">22 / 33</div>
      <img src="foto/2024-03_CIG/22.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">23 / 33</div>
      <img src="foto/2024-03_CIG/23.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">24 / 33</div>
      <img src="foto/2024-03_CIG/24.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">25 / 33</div>
      <img src="foto/2024-03_CIG/25.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">26 / 33</div>
      <img src="foto/2024-03_CIG/26.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">27 / 33</div>
      <img src="foto/2024-03_CIG/27.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">28 / 33</div>
      <img src="foto/2024-03_CIG/28.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">29 / 33</div>
      <img src="foto/2024-03_CIG/29.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">30 / 33</div>
      <img src="foto/2024-03_CIG/30.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">31 / 33</div>
      <img src="foto/2024-03_CIG/31.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">32 / 33</div>
      <img src="foto/2024-03_CIG/32.jpeg" style="width:100%">
  </div>
  <div class="mySlides">
    <div class="numbertext">33 / 33</div>
      <img src="foto/2024-03_CIG/33.jpeg" style="width:100%">
  </div>

  <!-- Next and previous buttons -->
  <a class="prev" onclick="plusSlides(-1)">&#10094;</a>
  <a class="next" onclick="plusSlides(1)">&#10095;</a>

  <!-- Image text -->
<!--
  <div class="caption-container">
    <p id="caption"></p>
  </div>
-->

</div>

<script>
let slideIndex = 1;
showSlides(slideIndex);

function plusSlides(n) {
  showSlides(slideIndex += n);
}

function currentSlide(n) {
  showSlides(slideIndex = n);
}

function showSlides(n) {
  let i;
  let slides = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("demo");
  let captionText = document.getElementById("caption");
  if (n > slides.length) {slideIndex = 1}
  if (n < 1) {slideIndex = slides.length}
  for (i = 0; i < slides.length; i++) {
    slides[i].style.display = "none";
  }
  for (i = 0; i < dots.length; i++) {
    dots[i].className = dots[i].className.replace(" active", "");
  }
  slides[slideIndex-1].style.display = "block";
  dots[slideIndex-1].className += " active";
  captionText.innerHTML = dots[slideIndex-1].alt;
}
</script>

